### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by krysclick** [hashicorp/terraform-provider-scaffolding-framework#114]
https://github.com/bflad/terraform-provider-aws/blob/master/.travis.yml

**Comment by bflad** [comment]
Hi again @krysclick 👋

The particular file that you linked is on a very old fork of the [Terraform AWS Provider codebase](https://github.com/hashicorp/terraform-provider-aws). TravisCI is no longer used for HashiCorp projects. I don't personally update the default branch of my forked repositories unless I have a particular use case that requires it.

If you are having trouble with the Terraform AWS Provider, I would suggest raising an issue on that repository or following their instructions for your particular request: https://github.com/hashicorp/terraform-provider-aws/issues
