### ISSUE TITLE
Update to a `.goreleaser.yml` valid for > v0

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-provider-scaffolding-framework#227]
I am having a bit of a headache recently updating the `.goreleaser.yml` config for Hashistack plugins to be compliant with v2, or even v1, as this is being enforced by the recent versions of the goreleaser Github Action and goreleaser module. I am working on trying to validate it with v1.25.1 as my digging around revealed this was the last version supporting Go 1.21, but it would be super helpful for the repository to be updated with an example that validates for > v0 goreleaser (other than locking to versions from a long time ago). I also assume that of all the examples this would be the best place to inquire as e.g. another Hashi repo still contains `--rm-dist` in the GHA config file for the goreleaser args.

Thanks for any updates.

Update: My personally modified version of the example is working for v1.25.1 goreleaser and 1.21 go for a packer plugin, and so that explains why the conflicts were recent, and helps inform that this is probably more of a >= 1.26 and 1.22 update.

**Comment by bflad** [comment]
Hey @mschuchard 👋 Thanks for raising this.

GoReleaser has been [preparing for a v2 release for awhile now](https://goreleaser.com/blog/goreleaser-v2/), with the [versioning of the configuration files being implemented less than a year ago](https://github.com/goreleaser/goreleaser/pull/4391). It seems like this tooling is now explicitly requiring the configuration versioning where for years it has previously had no configuration option for it nor enforcement. We'll certainly get this template repository and the [provider publishing documentation](https://developer.hashicorp.com/terraform/registry/providers/publishing) updated for the new changes in the coming days. In the meantime, the [GoReleaser v2 deprecations documentation](https://goreleaser.com/deprecations/#removed-in-v2) is the best place to refer for specific changes that need to happen to the release workflow and configuration file (in addition to adding `version: 2`).

One part I'm not personally clear on is any relation with GoReleaser to Go versioning, at least as it relates to GoReleaser v2. Theoretically, GoReleaser should be able to handle most versions of the Go toolchain given it is a separate binary. If that is not the case any more, that would be a surprise (at least to me), and potentially worth raising an issue upstream in https://github.com/goreleaser/goreleaser.

**Comment by ffalor** [comment]
Looks like, other than requiring `version` to be specified `changelog.skip` was changed to `changelog.disable` https://goreleaser.com/deprecations/#changelogskip

Everything else works

**Comment by mschuchard** [comment]
Glad to see my expectation that this was the best plugin SDK to report at was justified with both the quick action, and the fewest number of goreleaser deprecations among the plugins.

When I upgrade from 1.21/1.25.1 to 1.22/~>2 I will definitely reference the new template. Hopefully this saves other from the pain of digging through goreleaser git history and docs.

**Comment by mschuchard** [comment]
Thanks @bflad! What would be the easiest path to propagate this doc-ish update to the other plugin SDKs in the company stack?

**Comment by bflad** [comment]
@mschuchard can you elaborate on what you mean? If you're referring to something like updating https://github.com/hashicorp/terraform-plugin-framework/blob/main/.goreleaser.yml for v2, that shouldn't affect _provider_ development, only the release process of that particular SDK. It can happen separately, whenever.

**Comment by mschuchard** [comment]
https://github.com/hashicorp/packer-plugin-scaffolding is an example. There were updates four months ago that e.g. replaced `--rm-dist` with `--clean`, but it still needs what you did here.

**Comment by bflad** [comment]
Thank you for clarifying. 😄 I would reach out to the other projects individually -- there is no centralized team of Engineers or collective project that will be performing this effort. 👍

**Comment by mschuchard** [comment]
Yeah I kind of gathered as much from past experience discussing Vault with TF team members. Thanks for the update!
